function feat = generateFeatures(x)
% Get standard deviation of the signal as feature
stdev = std(x);

% Get total power of the signal
SE = dsp.SpectrumEstimator('SampleRate',1800);
pxx = step(SE,x);
tpwr = trapz(pxx,1);

% Preprocessing to remove offset and rectify the raw signal
x = abs(detrend(x));

% Find the linear envelope using a low pass filter (8 columns)
envavg = mean(doLPFilter(x),1);


feat = [stdev, envavg, tpwr];

end

function y = doLPFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 12-Apr-2017 12:53:45

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N    = 2;     % Order
    % F3dB = 15;    % 3-dB Frequency
    % Fs   = 1800;  % Sampling Frequency
    %
    % h = fdesign.lowpass('n,f3db', N, F3dB, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.92598396973189 0.928627086124807], ...
        'ScaleValues', [0.000660779098230377; 1]);
end

s = double(x);
y = step(Hd,s);
end